JohnstonCode/svn-scm

- package.json
> Formal display name and description

- src/commands.ts
- tsconfig.json
Commit was not working at all with VsCode 1.18.0.
(Didn't test with an older version)
> Fixing unable to commit problem

- src/repository.ts
This should solve the problem of slowness when switching branches
> Fixed debounce calling

- package.json
- src/extension.ts
- src/svn.ts
> Added support to configure the path to the svn executable

- package.json
- src/extension.ts
- src/svn.ts
Reverts JohnstonCode/svn-scm#43
> Revert "Added support to configure the path to the svn executable"

- src/svn.ts
> Fixed "Cannot read property '1' of null" (Close #45)

- package.json
- src/repository.ts
Reverts JohnstonCode/svn-scm#50
> Revert "Fixed commit for all changed files (Close #44)"

- src/decorators.ts
- src/repository.ts
- src/statusBar.ts
- src/util.ts
and added statusbar spin on switching branch
Based on GIT extension.
> Improved workspace events changes

- CHANGELOG.md
- src/commands.ts
- src/model.ts
- src/svn.ts
Currently it will always ask which repository to revert file.
With the fix, it automatically detects the repository
> Fixed SVN revert for multiple svn folders

- .gitignore
- .travis.yml
- .vscode/launch.json
- .vscodeignore
- README.md
- package-lock.json
- package.json
- src/test/extension.test.ts
- src/test/index.ts
Note: Enable in your repo the travis-ci
Related #74
> Added initial support to tests (#74)

- package.json
- src/commands.ts
- src/svn.ts
- src/svnRepository.ts
This pull request adds the ability to generate a patch of the current changes in the workspace.
> Feature | Add SVN Patch 

- src/extension.ts
- src/model.ts
- src/repository.ts
- src/statusBar.ts
- src/svnContentProvider.ts
- src/uri.ts
- src/util.ts
* For, example, if you change branch with command line, the current branch and file diff is updated
* Update branch name only have changes in repository, not every status update
* On switching branch, prevent multiple icon update
> Improved external changes

- icons/dark/remove.svg
- icons/light/remove.svg
- package.json
- src/commands.ts
- src/model.ts
- src/repository.ts
- src/svn.ts
- src/svnRepository.ts
* On commit, you can choose the "Changes" or one changelist
* Can add or remove files in changelist
* For renamed files, the old file is commited on commit
See #95 and #99
> Added support to changelists (Close #95,#99)

- .bithoundrc
- README.md
Create account at https://www.bithound.io/
> Added bitHound code analysis

- package.json
- src/commands.ts
@JohnstonCode 
Done to close #99
> Added options to ignore changelist on commit (#99 and #120)

- package.json
- src/repository.ts
> Add configuration option for the frequency that branches are checked remotely

- src/commands.ts
- src/repository.ts
- src/svnContentProvider.ts
- src/uri.ts
- src/util.ts
On open file with head, log or patch, the document is read only.
If repository is updated, that files are updated.
> Fixed document title for: file head, log and patch (Close #145)

- .travis.yml
- appveyor.yml
- src/commands.ts
- src/extension.ts
- src/model.ts
- src/test/commands.test.ts
- src/test/index.ts
- src/test/repository.test.ts
- src/test/testUtil.ts
> Optimize tests

- package.json
- src/repository.ts
Added config options to configure status count (Close #144)
> Added config options to configure status count (Close #144)

- src/util.ts
Improved detection of support for decoration provider(Close #149)
> Improved detection of support for decoration provider(Close #149)

- src/commands.ts
- src/repository.ts
Use "Save As"
We need use a temporary file for change the title.
> Added ability to save patches (Close #155)

- package.json
- src/commands.ts
- src/repository.ts
- src/svnContentProvider.ts
- src/svnRepository.ts
Has two palette commands, one for current in editor, and another for all project.
> Added support for show diff patch for selected

- package.json
- src/commands.ts
- src/repository.ts
- src/statusBar.ts
- src/statusParser.ts
- src/svnRepository.ts
Removed locked items in changes lists (Close #199)
Added cleanup command
Check repository is incomplete and resolve in statusbar
> Removed locked items in changes lists (Close #199)

- package.json
- src/changelistItems.ts
- src/commands.ts
- src/test/commands.test.ts
* Removed "Remove Changelist"
* If has changelist, show "Remove" in picks
> Improved Changelists

- README.md
Trying out a different layout to organize settings. I'll update the configs that are missing afterwards.
> Try out new settings table layout

- package-lock.json
- package.json
- src/model.ts
- src/repository.ts
- src/svn.ts
The VISX file reduced size from 1.8MB to 880KB
> Replaced micromatch with minimatch

- package.json
- src/repository.ts
Note: update README.md before new release
> Added config option to count pending changes (Close #237)

- src/commands.ts
- src/messages.ts
- src/svn.ts
* Added warning message if empty (Close #235,#240)
* Added info of reason for commit failed (Close #236)
> Improved commit (Close #235, #236, #240)

- README.md
- package.json
- src/common/types.ts
- src/repository.ts
- src/statusBar.ts
- src/statusParser.ts
- src/svnRepository.ts
- src/util.ts
Reverts JohnstonCode/svn-scm#285
> Revert "Show incoming changes files (Close #207)"

- src/commands.ts
- src/svnRepository.ts
Fix only the commit
Changelist not working on folders, see [Changelist Limitations](http://svnbook.red-bean.com/en/1.7/svn.advanced.changelists.html#svn.advanced.changelists.limitations)
> Fixed commit new files/folders from changelist (Close #292)

- package-lock.json
- package.json
- src/svnRepository.ts
- src/test/testUtil.ts
The problem is in decode characters in SVN, ignore defined environments.
To work, use a file with UTF-8 and pass the --encoding UTF-8 argument.
> Fixed commit message with chinese character (Close #286)

- README.md
- package.json
- src/commands.ts
- src/repository.ts
- src/svnRepository.ts
After a long work:
* Option to configure action for deleted files (none, prompt, remove)
* Option to ignore some files (Ex. compiled file)
> feat: Prompt action for deleted file (Close #314)

- src/extension.ts
- src/helpers/configuration.ts
- src/svnFinder.ts
If the the executable of `svn` not found, add a button to allow to search and update the `svn.path`.
> feat: Added option to search the executable of svn

- src/commands.ts
- src/repository.ts
- src/svnRepository.ts
> fix: Disable branch switching without common ancestor #372

- package.json
- src/commands.ts
> changes with PREV

- .releaserc.json
> ci: dont think the plugins section is needed

- README.md
> docs: Added link to blamer-vs in readme fix #383

- package-lock.json
- package.json
> chore: Added commitizen to dev deps and added npm script

- src/svnFinder.ts
> Fix svn not found

- package.json
- src/commands/changeList.ts
> feat: Added set change list to explorer context

- src/commands/changeList.ts
- src/common/types.ts
- src/model.ts
- src/repository.ts
> fix: Set changelist context menu

- package.json
> fix: Changed "Pull selected changes" to "Update selected" to better reflect svn command name

- package-lock.json
- package.json
https://code.visualstudio.com/blogs/2018/11/26/event-stream
> chore: Updated deps due to events-stream issue

- package-lock.json
- src/model.ts
- src/repository.ts
- src/test/extension.test.ts
- src/test/globMatch.test.ts
- src/util/globMatch.ts
> fix: Created matchAll function wrapper for minimatch so dir globs are properly ignored

- .vscode/launch.json
- src/pathNormalizer.ts
- src/svnRI.ts
- src/test/pathNormalizer.test.ts
> Fix path normalizer

- package-lock.json
- src/historyView/itemLogProvider.ts
> fix: Fixed windows network drive issues

- .releaserc.json
- build.yml
> ci: Deploy fix

- src/model.ts
- src/svn.ts
- src/svnContentProvider.ts
> refactor: Svn errors now show the repo name in the output channel

- build.yml
> ci: Using npm ci

- src/commands/addToIgnoreExplorer.ts
> fix: Fixed ignore folder context on explorer (close #438)

- build.yml
- package-lock.json
- package.json
- src/test/index.ts
- src/test/runTest.ts
- src/test/testUtil.ts
> chore: updated ts and vs

- package-lock.json
- package.json
> chore: updated mocha-junit-reporter

- package-lock.json
- package.json
> fix: Removed use of origional fs to allow extension to work remotely

- src/svnRepository.ts
> fix: Diffs now use internal diff flag

- src/types/vscode.proposed.d.ts
Update vscode.proposed.d.ts with vscode 1.26
> refactor: Updated vscode.proposed.d.ts

- package.json
- src/commands.ts
- src/commands/pickCommitMessage.ts
> feat: Added support to pick a previous commit message (close #358)

- src/treeView/nodes/incomingChangeNode.ts
> fix: Fixes single click diff on incoming change tree

- package.json
> fix: Readded activation event

- .github/workflows/main.yml
- .vscodeignore
> Added revert package.json step

- src/commands/changeList.ts
- src/input/revert.ts
- src/messages.ts
- src/repository.ts
- src/util.ts
> chore: Removed unnecessary awaits

- .github/workflows/main.yml
- .vscodeignore
https://help.github.com/en/github/automating-your-workflow-with-github-actions/persisting-workflow-data-using-artifacts#uploading-build-and-test-artifacts
> chore: Added upload artifacts (#710)

- .github/workflows/main.yml
> chore: added npm cache to build

- package-lock.json
- package.json
- src/messages.ts
> chore: fixed webview errors in tests

- src/messages.ts
> fix: Fixed CSP policy for commit page

- src/watchers/repositoryFilesWatcher.ts
Turns out the custom fs.watch I put in completely destroyed my system during an svn checkout...
This debounces it.
> fix: Debounce repo watcher

- src/encoding.ts
> fix: Added check for jschardet constants

- src/tempFiles.ts
- src/test/tempFiles.test.ts
> fix: temp files are created in uid directory

- package.json
- src/commands.ts
- src/commands/search_log_by_revision.ts
- src/commands/search_log_by_text.ts
- src/common/types.ts
- src/contexts/isSvn18orGreater.ts
- src/extension.ts
- src/repository.ts
- src/svnContentProvider.ts
- src/svnRepository.ts
> feat: Added log search commands

- README.md
Added workflow status using https://shields.io/
See: https://github.com/badges/shields/blob/c455993a4d307823a1f551955e9300cd3bc6e2c2/services/github/github-workflow-status.service.js
> chore: Added workflow status

- package-lock.json
- package.json
- src/historyView/common.ts
> chore: replaced date-fns with dayjs

- src/util.ts
- src/watchers/repositoryFilesWatcher.ts
> fix: file changes on windows not registering

- src/repository.ts
BTW, there is no package-lock.json in repository, is it ok?
> fix: Capitalised conflicts change group name

- package.json
Let's be more consistent with other UI
> fix: made copy titles more consistent with other UIs

- src/commands/openFile.ts
> fix: sourceControl.changesLeftClick setting to 'Open' now works

- src/vscodeModules.ts
- webpack.config.js
> fix: Fixed webpack dep issue on remote vscode

- package.json
- src/commands.ts
- src/commands/pickCommitMessage.ts
- src/repository.ts
- src/svn.ts
- src/svnRepository.ts
> feat: Added config option to show previous commits by user

- README.md
- package.json
> chore: add checkout instructions
