src/commands.ts
src/svn.ts

This should work with multiple projects in the same versioning.
Example:
https://plugins.svn.wordpress.org/
You can testing using https://plugins.svn.wordpress.org/jetpack

Added support to subpath for project, in switching branches

---

src/extension.ts
src/svn.ts

Added specific output channel (Close #37)

---

package.json
src/extension.ts
src/svn.ts

Added support to configure the path to the svn executable

---

CHANGELOG.md
src/repository.ts

Currently, each save, it generates a list request of branches.
This pull request solves the issue

Reduced calls to branch listings

---

package.json

If the config "svn.multipleFolders.ignore" is globally true, on open a git project, High CPU usage

Added to ignore .git and .hg in multiple folders

---

CHANGELOG.md
package.json
src/model.ts

* Not check SVN version if folder not contains ".svn" folder
* Fixed ignored folder for multifolder svn to work with Windows

Improved multiple svn folders

---

src/svn.ts
src/svnRepository.ts

See http://svnbook.red-bean.com/en/1.8/svn.ref.svn.html#svn.ref.svn.sw.force_log
Note: SVN log show quotes for arguments if contains space.
Old: `svn commit -m test message readme.md`
New: `svn commit -m 'test message' readme.md`

Fixed commit when message is a existent file (Close #221)

---

src/commands.ts
src/repository.ts
src/svn.ts

* Default show last username
* If press "ESC", not prompt more
* Improved detection of authentication

Improved Authentication (Close #219)

---

package.json
src/svn.ts

Added configuration parameter svn.default.encoding:
Encoding of svn output if the output is not utf-8. When this parameter is null, the encoding is automatically detected. Example: 'svn.default.encoding: windows-1252'.

Added configuration parameter svn.default.encoding

---

src/commands.ts

If file is deleted or renamed, in console error show `ENOENT: no such file or directory`

Fixed error: ENOENT: no such file or directory

---

src/svn.ts

SVN 1.6 not has the `wcroot-abspath` entry in XML, the current directory is `wcroot-abspath`

Fixed compatibility with SVN 1.6

---

src/svn.ts

Some users change the default `files.encoding`.
With this pull, not need change the `svn.default.encoding` in some cases

Use the "files.encoding" for default encoding

---

package.json
src/commands.ts
src/model.ts
src/svn.ts

If working copy is old (Ex. 1.6) and the client is new (Ex. 1.9), show a prompt to upgrade the working copy

Added check for old working copy

---

src/repository.ts

Order:
* Changes
* Conflicts
* Changelist
* Unversioned
* Remote changes
Recreate Unversioned and Remote changes only if the number of changelist id changed

fix: Fixed order of resources groups

---

package.json
src/commands.ts

A alternative for `svn.refresh.remoteChanges` option

feat: Added refresh button for remote changes (#366)

---

package.json
src/commands/command.ts

* Removed revert confirmation alert
* Fixed menu for revert selection in diff editor
* Fixed register command when diff is true

fix: Removed revert confirmation alert (close #395)

---

.vscodeignore

https://github.com/Microsoft/vscode/issues/62687
Don't include `*.map` files in the VS Code extension bundle vsix

Don't include *.map in extension bundle

---

src/repository.ts
src/svn.ts

For remote operations in `repository.ts` we need use the `retryRun`

fix: Fixed credentials for remote changes (Close #401)

---

package.json
src/resource.ts

feat: Added config option to choose changes left click command

---

src/resource.ts

In VSCode 1.27 has renamed the `abbreviation` to `letter`

fix: Fixed svn status letter in file explorer

---

src/contexts/checkActiveEditor.ts
src/extension.ts
src/model.ts

My idea to improve `model.ts`:
- Create more events (When necessary)
- Move code to another files and use events

refactor: Removed check active editor from model (#443)

---

src/test/istanbultestrunner.ts

Fixed the message: `useColors is DEPRECATED and will be removed from a future version of Mocha. Instead, use the "color" option`
Note: current Mocha is 6.0.2, but, the latest `@types/mocha` is 5.2.6

test: Fixed Mocha deprecated warning

---

src/svnRepository.ts
src/test/commands.test.ts

Fix the message:
```
Tests exited with code: 0
stack trace: Error: spawn /usr/local/bin/svn ENOENT
at Process.ChildProcess._handle.onexit (internal/child_process.js:229:19)
at onErrorNT (internal/child_process.js:406:16)
at process._tickCallback (internal/process/next_tick.js:63:19)
Constructor called in sync fashion, test-only
Error
at new Repository (/Users/vsts/agent/2.148.1/work/1/s/out/svnRepository.js:9:4963)
at Object.<anonymous> (/Users/vsts/agent/2.148.1/work/1/s/src/test/svnRepository.test.ts:23:30)
at Generator.next (<anonymous>)
at __awaiter (/Users/vsts/agent/2.148.1/work/1/s/out/test/svnRepository.test.js:7:71)
at new Promise (<anonymous>)
at __awaiter (/Users/vsts/agent/2.148.1/work/1/s/out/test/svnRepository.test.js:3:12)
at Context.test …
```

test: Fixed spawn ENOENT for svnRepository.test.ts

---

src/repository.ts
src/test/index.ts
src/watchers/repositoryFilesWatcher.ts

The new class `RepositoryFilesWatcher` filter all files events from workspace
* Ignore events in `.svn/tmp`
* Ignore events outside of root of repository
* Can use events only in workspace, only .svn folder or both

refactor: Removed fsWatcher from repository

---

src/decorators.ts
src/repository.ts

The solution: sequentialize executation by name

fix: Fixed high cpu usage by parallel svn processes (close #463)

---

src/commands/command.ts
src/commands/deleteUnversioned.ts
src/commands/openFile.ts
src/fs/exists.ts
src/fs/readdir.ts
src/fs/stat.ts
src/historyView/common.ts
src/historyView/repoLogProvider.ts
src/model.ts
src/svnRepository.ts
src/tempFiles.ts
src/test/commands.test.ts
src/test/istanbultestrunner.ts
src/test/repository.test.ts
src/test/testUtil.ts
src/tools/generateConfigSectionForReadme.ts
src/treeView/nodes/incomingChangeNode.ts
src/types/original-fs.d.ts
src/util.ts
tslint.json

* Fixed .asar file locking
* Replaced all usage of `"fs"` with `"original-fs"`
* Blacklisted usage of `"fs"` module
https://electronjs.org/docs/tutorial/application-packaging#treating-an-asar-archive-as-a-normal-file

fix: Fixed .asar file locking (close #437)

---

package-lock.json
package.json
src/svn.ts
src/types/iconv-lite.d.ts
src/vscodeModules.ts
tslint.json

* Removed dev dependency of `iconv-lite` in favor `iconv-lite.d.ts`
* Deny direct import for `iconv-lite` and `jschardet`
* Don't try load vscode modules from `node_modules` directory

refactor: Refactored usage of vscode modules

---

src/svnRepository.ts
src/test/repository.test.ts

New format: `<n> files commited: revision <i>`, where `<n>` is the number of sended files and `<i>` the commited revision

fix: Improved commit message notification (close #545)

---

README.md
package.json
src/extension.ts
src/fs/access.ts
src/fs/index.ts
src/helpers/configuration.ts
src/model.ts
src/proposed.ts

Currently we can not publish extensions with `"enableProposedApi"= true`.
This pull make two options:
* Add to allowed use of proposed API on `product.json`
* Set `"enableProposedApi"= true` after install, to allow start with `code --enable-proposed-api johnstoncode.svn-scm`

feat: Added option to enable proposed features

---

package.json
src/commands.ts
src/commands/revertAll.ts
src/commands/revertExplorer.ts
src/input/revert.ts
src/repository.ts
src/svnRepository.ts

feat: Added support to revert from explorer
fix: Check files before prompt depth on revert (close #606)

feat: Added support to revert from explorer (close #606)

---

src/model.ts

The code missed an "await" at the place where the new isSvnFolder
function is used.  Function isSvnFolder always returns a valid
Promise, which was treated like a boolean "true" in the "if".

Fix trying to open every file as a repo (close #621)

---

src/historyView/common.ts

If a commit has no author defined, getCommitIcon would finally crash
at creating the md5 of undefined.  With this patch the non-gravatar
default icon is used instead, for commits with an undefined author.

Fix commit icon for undefined author

---

build.yml

chore: Stop windows and OSX builds from generating coverage reports

---

package.json

@types/vscode version needs to match engine req in package.json

chore: Stop greenkeeper updates vscode types

---

package-lock.json
package.json
tsconfig.json

The current version of NODE in vscode "1.26.x" is "8.9.x", look: https://code.visualstudio.com/updates/v1_26#_nodejs-update
The next update of NODE is in:
* vscode "1.31": https://code.visualstudio.com/updates/v1_31#_nodejs-update
* vscode "1.36": https://code.visualstudio.com/updates/v1_36
If in the future want update the minimal version of VSCODE, is good to update the value of `target` in `tsconfig.json`

chore: Stop greenkeeper updates node types

---

src/common/types.ts
src/statusParser.ts

Lock status was not properly recognized when 'lock' object was present in the status response from the server.
Doesn't implement #624, but helps with the locks issue mentioned there.

checking for lock field when parsing xml entries

---

.github/workflows/main.yml

chore: build now uses macos latest

---

src/svnRepository.ts

Currently, if you have just the root of your repository checked out and you use svn update to "checkout" each branch (instead of having multiple checked out branches, e.g.), the extension doesn't correctly show the current branch when looking at the logs. Instead, it shows the logs for the root of the repo, which is not right.
This MR makes svn info run in the workspaceRoot, instead of the repo root.

fix: Stop retrieving info of repo root

---

package.json
src/common/types.ts
src/diffParser.ts
src/extension.ts
src/historyView/branchChangesProvider.ts
src/historyView/common.ts
src/repository.ts
src/svnRepository.ts
src/util.ts
src/watchers/repositoryFilesWatcher.ts

this adds a new tree view that gives you a nice listing of all the files that changed between the current branch and the branch it was copied from.
tooltip:
clicking something marked M will open up a diff:

feat: Added Branches tree view

---

src/svnRepository.ts

Found an issue with pull request #728. The CWD is wrong when running commands against a URL.

fix: Fix cwd when running svn commands for remoteRepository

---

README.md
package.json

Noticed this typo when in the VS Code pref menus, thought it was worth fixing.

chore: Fixed typos

---

package-lock.json
package.json
src/historyView/common.ts
src/historyView/itemLogProvider.ts
src/historyView/repoLogProvider.ts

feat: Added pretty descriptions to treeview

---

package.json
src/commands.ts
src/commands/removeUnversioned.ts
src/contexts/checkActiveEditor.ts
src/contexts/isSvn19orGreater.ts
src/contexts/openRepositoryCount.ts
src/diffParser.ts
src/extension.ts
src/messages.ts
src/repository.ts
src/resource.ts
src/statusParser.ts
src/svn.ts
src/svnContentProvider.ts
src/svnRepository.ts
src/test/testUtil.ts
src/treeView/dataProviders/svnProvider.ts
src/util.ts
src/vscodeModules.ts

The only thing that I would like to discuss with you is `logOutput`. I've made it public since I think we must inform user whatever actually happened.
I propose a global function, maybe in utils, which will log everything to outputChannel. Under the hood it will emit events, which output channel will be subscribed to.

feat: Add remove unversioned command

---

src/common/types.ts
src/repository.ts
src/types/keytar.d.ts
src/vscodeModules.ts

Instead of find a way to save auth, use keytar as an alternative.
See: https://code.visualstudio.com/api/advanced-topics/remote-extensions#persisting-secrets

fix: Fixed repeated auths prompt (close #652)

---

src/historyView/repoLogProvider.ts

This fixes being unable to diff a file between revisions due to sparse checkout. Instead of trying to figure out where the file lives on the filesystem, we'll simply use the remote URI to diff the file.

fix: Use remote URI to retrieve file for repo log

---

package.json
src/encoding.ts
yarn.lock

Trialling using `chardet` over `jschardet`. `chardet` is only used if `svn.experimental.detect_encoding` is `true`

feat: added new experimental encoding detection

---

package.json
src/encoding.ts

This adds a new config option `svn.experimental.encoding_priority` which takes an array of encoding types and prioritise them based on order. For example `["UTF-8", "GB18030", "windows-1251"]` will prioritise `UFT-8` then `GB18030` ect. If there are no matches it will just return null and will either use `default.encoding` or `UTF-8`.

fix: added experimental encoding priority list

---

src/historyView/common.ts
src/resource.ts
src/uri.ts
webpack.config.js

fix: Fixed styling on "Commit selected" page

---

package.json
src/repository.ts
src/svnRepository.ts

I think use `matchBase` option is better.

fix: use matchBase option when match ignoreList

---

package.json
src/commands.ts
src/commands/merge.ts
src/common/types.ts
src/helpers/branch.ts
src/repository.ts
src/statusbar/syncStatusBar.ts
src/svnRepository.ts

As I (and other #618) was looking for this feature for quite a while now, I just drafted it. I am not typescript, vscode & svn expert so am really happy for any improvement ideas.

feat: Added Merge command

---

package.json
yarn.lock

fix: https://github.com/JohnstonCode/svn-scm/issues/973#issuecomment-1015043455
```
Version: 1.64.0-insider (user setup)
Commit: 7ae7f9d40b82a0f1a49d8ad180d27e16812ad95e
Date: 2022-01-18T05:16:47.915Z
Electron: 13.5.2
Chromium: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Windows_NT x64 10.0.18363
```

fix: Missing dependency: iconv-lite

---

src/svnRepository.ts

When determining if a branch is a copy, the entire log is fetched, but only the first commit is checked. This is problematic if the branch is not a copy, and the commit log is massive. A large enough log will currently crash VS Code. 
This fix limits pulling only the first log. Fixes #1539

fix: add --limit=1 when determining branch copy source

---

src/watchers/repositoryFilesWatcher.ts

Currently, when files are changed, there is an exception that breaks the SVN extension.
```
2022-12-20 17:21:44.105 [error] TypeError: Cannot read properties of undefined (reading 'fire')
at /home/mreisner/.vscode-server/extensions/johnstoncode.svn-scm-2.15.5/out/extension.js:2:278235
```
This pull request binds the call to `this.repoWatch` to the `RepositoryFilesWatcher` object so that this exception isn't triggered.

fix: bind repoWatch to RepositoryFilesWatcher object
